# Generated by Django 5.1 on 2024-08-16 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentcourse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcourse',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
