# Generated by Django 5.1 on 2024-08-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentcourse_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcourse',
            name='created_at',
        ),
    ]
