# Generated by Django 5.1 on 2024-08-16 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_paymentcourse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcourse',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 16, 13, 14, 54, 55463, tzinfo=datetime.timezone.utc)),
        ),
    ]
